feat(backend): get_limit
keep-starknet-strange/vault pull request #61
Opened 2024-04-16 16:24 UTC by Gift-Naomi

2024-04-17 14:10 UTC, LucasLvy requested changes
you need to add tests + run `pnpm fix`

2024-04-17 14:10 UTC, LucasLvy commented on backend/src/routes/getLimit.ts
> +        .execute();
```suggestion
      const { currentLimit } = await fastify.db.select({limit: mockLimit.limit).from(mockLimit).where(eq(mockLimit.address, address));
```

2024-04-17 15:52 UTC, Gift-Naomi commented on backend/src/routes/getLimit.ts
> +        .execute();
I have made the changes.

2024-04-18 09:43 UTC, LucasLvy requested changes

2024-04-18 09:43 UTC, LucasLvy commented on backend/test/getLimit.test.ts
> +          limit: '7714789860048896',
```suggestion
          limit: '7714789860.048896',
```

2024-04-18 09:43 UTC, LucasLvy commented on backend/src/routes/getLimit.ts
> +        .where(eq(mockLimit.address, address));
limit shouldn't be an array it should be just the value

2024-04-19 09:06 UTC, LucasLvy requested changes

2024-04-19 09:06 UTC, LucasLvy commented on backend/src/db/schema.ts
> +  limit: text('limit'),
```suggestion
  limit: text('limit'),
  blockTimestamp: timestamp('block_timestamp', { withTimezone: false }),
```

2024-04-19 09:06 UTC, LucasLvy commented on backend/src/routes/getLimit.ts
> +        .where(eq(mockLimit.address, address));
```suggestion
      const limit = await fastify.db
        .select({ limit: mockLimit.limit })
        .from(mockLimit)
        .where(eq(mockLimit.address, address))
        .orderBy(desc(mockLimit.blockTimestamp))
        .limit(1);
```

2024-04-22 08:41 UTC, LucasLvy approved these changes

2024-04-22 08:55 UTC, merged